"""Generate table2_baselines.tex, baseline_numbers.tex and verdict_matrix.json
from baseline_final_results.json (+ verifier's crosslm_c5_heldout.json and
distinct_ci.json). POST-HOC SECONDARY analysis. No hand-typed numbers."""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
V = HERE.parent / "verify"
R = json.load(open(HERE / "baseline_final_results.json"))
X = json.load(open(V / "crosslm_c5_heldout.json"))
DC = json.load(open(V / "distinct_ci.json"))

ROWS = [("lm_perplexity", "Perplexity"), ("self_similarity", "Self-similarity"),
        ("ioi_hist_js", "IOI-histogram JS"), ("onset_f1_50ms", "Onset F1, 50\\,ms"),
        ("onset_f1_20ms", "Onset F1, 20\\,ms")]
COLS = [("C1_timing_jitter", "Jitter"), ("C1s_sparse_jitter", "Sparse errors"),
        ("C2_anchor_shift", "Shift"),
        ("C3_type_shuffle", "Type shuffle"), ("C4_loop_collapse", "Loop"),
        ("C5_blandification", "Common pattern"), ("C8_bar_shuffle", "Window shuffle"),
        ("C6_density_scale", "Note rate"), ("C7_burst_insert", "Burst")]
SYM = {"DETECTS": r"\checkmark", "BLIND": r"$\circ$", "REWARDS": r"$\times$", "N/A-by-design": "--"}
cell = {(r["baseline"], r["probe"]): r for r in R["results"]}

matrix = {}
for b, _ in ROWS:
    matrix[b] = {}
    for p, _ in COLS:
        lab = cell[(b, p)]["label"]
        if lab not in SYM:
            raise SystemExit(f"unexpected label {lab} for {b} {p}")
        matrix[b][p] = lab
for (b_, p_), r_ in cell.items():
    if r_["label"] == "REWARDS":
        assert r_["dose_ci995"][0] > 0 and r_["contrast_ci995"][0] > 0, (b_, p_)
matrix["chartgeneval_measurement"] = {p: R["chartgeneval_measurement_row"][p]["label"] for p, _ in COLS}
assert all(v == "DETECTS" for v in matrix["chartgeneval_measurement"].values())

# ---------------- table
L = []
L.append("% AUTO-GENERATED by make_tex.py from baseline_final_results.json -- do not edit numbers by hand.")
L.append("% POST HOC SECONDARY analysis (not prespecified). Needs amssymb (\\checkmark), booktabs, graphicx.")
L.append("\\begin{table}[t]")
L.append("\\centering")
L.append("\\caption{Common statistics under the nine controlled errors on the same 80 held-out songs"
         " (post hoc secondary analysis, not prespecified)."
         " \\checkmark: passes the test of Table~\\ref{tab:results};"
         " $\\circ$: exactly unchanged at every seed and strength;"
         " $\\times$: moves toward the conventionally better value, with both 99.5\\% intervals excluding 0"
         " (lower perplexity; higher self-similarity, if higher is read as better);"
         " --: unchanged by design (the statistic sees only note times; the edit changes only note types)."
         " Onset F1 (maximum matching, against the unedited chart) is exactly 1 whenever no note moves beyond the tolerance,"
         " so at 50\\,ms it detects the shift only at 60\\,ms and at 20\\,ms it detects jitter only at $\\pm$30\\,ms."
         " Last row: the matched ChartGenEval measurement for each edit (Table~\\ref{tab:results}).}")
L.append("\\label{tab:baselines}")
L.append("\\vspace{2pt}{\\fontsize{9}{11}\\selectfont")
L.append("\\setlength{\\tabcolsep}{2pt}\\newcommand{\\blcell}[1]{\\makebox[13pt]{#1}}")
L.append("\\setlength{\\lightrulewidth}{0.6pt}\\setlength{\\cmidrulewidth}{0.6pt}% print stroke floor, as in paper.tex")
L.append("\\begin{tabular}{@{}l" + "c" * len(COLS) + "@{}}")
L.append("\\toprule")
L.append(" & \\multicolumn{3}{c}{Timing} & \\multicolumn{4}{c}{Pattern, repetition} & \\multicolumn{2}{c}{Density}\\\\")
L.append("\\cmidrule(lr){2-4}\\cmidrule(lr){5-8}\\cmidrule(l){9-10}")
L.append("Statistic & " + " & ".join(f"\\rotatebox{{90}}{{{name}}}" for _, name in COLS) + "\\\\")
L.append("\\midrule")
for b, name in ROWS:
    L.append(f"{name} & " + " & ".join("\\blcell{" + SYM[matrix[b][p]] + "}" for p, _ in COLS) + "\\\\")
L.append("\\midrule")
L.append("ChartGenEval & " + " & ".join("\\blcell{" + SYM[matrix["chartgeneval_measurement"][p]] + "}" for p, _ in COLS) + "\\\\")
L.append("\\bottomrule")
L.append("\\end{tabular}}")
L.append("\\end{table}")
(HERE / "table2_baselines.tex").write_text("\n".join(L) + "\n")

# ---------------- macros
def num(x, n):
    s = f"{x:.{n}f}"
    return s.replace("-", "$-$") if False else s


def m(x, n, sign=False):
    s = f"{x:+.{n}f}" if sign else f"{x:.{n}f}"
    return "\\ensuremath{" + s.replace("-", "-") + "}"


def ci(lo, hi, n, sign=True):
    f = (lambda v: f"{v:+.{n}f}") if sign else (lambda v: f"{v:.{n}f}")
    return "\\ensuremath{[" + f(lo) + "," + f(hi) + "]}"


def raw_contrast(r):
    """strongest edit minus matched control in the metric's own units (un-oriented)."""
    sgn = -1.0 if r["worse_direction"] == "increase" else 1.0
    lo, hi = r["contrast_ci995"]
    a, b = sgn * lo, sgn * hi
    return sgn * r["contrast_mean"], min(a, b), max(a, b)


macros = []
src = {}


def add(name, value, source):
    macros.append((name, value)); src[name] = source


for key, tag in (("C4_loop_collapse", "Loop"), ("C5_blandification", "Common")):
    r = cell[("lm_perplexity", key)]
    sm = r["song_mean_by_dose"]
    add(f"BlPpl{tag}After", m(sm["d3"], 2), f"lm_perplexity/{key}: song_mean_by_dose.d3")
    add(f"BlPpl{tag}Pct", m(abs(r["strongest_minus_unedited_pct"]), 0), f"lm_perplexity/{key}: |strongest_minus_unedited_pct| (drop, %)")
    d, lo, hi = raw_contrast(r)
    add(f"BlPpl{tag}Delta", m(d, 2, True), f"lm_perplexity/{key}: strongest minus matched control (raw units)")
    add(f"BlPpl{tag}DeltaCI", ci(lo, hi, 2), f"lm_perplexity/{key}: 99.5% CI of raw contrast")
    add(f"BlPpl{tag}Rho", m(r["dose_statistic_mean"], 3, True), f"lm_perplexity/{key}: oriented rank correlation (positive = toward better)")
    add(f"BlPpl{tag}RhoCI", ci(*r["dose_ci995"], 3), f"lm_perplexity/{key}: 99.5% CI of oriented rho")
add("BlPplUnedited", m(cell[("lm_perplexity", "C4_loop_collapse")]["song_mean_by_dose"]["official"], 2), "lm_perplexity: song_mean_by_dose.official")
cross = [X[k]["delta_ppl_song_mean"] for k in ("A_even_tri", "B_odd_tri", "C_full_4gram")]
cross_hi = max(X[k]["delta_ci995"][1] for k in ("A_even_tri", "B_odd_tri", "C_full_4gram"))
add("BlPplCommonCrossMin", m(min(abs(c) for c in cross), 2), "verify/crosslm_c5_heldout.json: min |delta_ppl_song_mean| over 3 separately fitted scorers")
add("BlPplCommonCrossMax", m(max(abs(c) for c in cross), 2), "verify/crosslm_c5_heldout.json: max |delta_ppl_song_mean| over 3 separately fitted scorers")
add("BlPplCommonCrossWorstUpper", m(cross_hi, 2, True), "verify/crosslm_c5_heldout.json: largest 99.5% upper bound of delta over 3 scorers")
for key, tag in (("C4_loop_collapse", "Loop"), ("C5_blandification", "Common")):
    r = cell[("self_similarity", key)]
    sm = r["song_mean_by_dose"]
    add(f"BlSelfSim{tag}After", m(sm["d3"], 3), f"self_similarity/{key}: song_mean_by_dose.d3")
    add(f"BlSelfSim{tag}Pct", m(r["strongest_minus_unedited_pct"], 0), f"self_similarity/{key}: strongest_minus_unedited_pct (rise, %)")
add("BlSelfSimUnedited", m(cell[("self_similarity", "C4_loop_collapse")]["song_mean_by_dose"]["official"], 3), "self_similarity: song_mean_by_dose.official")
r = cell[("onset_f1_50ms", "C1_timing_jitter")]
assert r["replicate_level_exactly_invariant"] and r["song_mean_by_dose"]["d3"] == 1.0
add("BlFOneFiftyJitter", m(r["song_mean_by_dose"]["d3"], 3), "onset_f1_50ms/C1: song mean at +-30 ms (every replicate exactly 1)")
r = cell[("onset_f1_50ms", "C2_anchor_shift")]
assert r["song_mean_by_dose"]["d1"] == 1.0 and r["song_mean_by_dose"]["d2"] == 1.0
add("BlFOneFiftyShiftSixty", m(r["song_mean_by_dose"]["d3"], 3), "onset_f1_50ms/C2: song mean at 60 ms shift (exactly 1 at 15, 30 ms)")
r = cell[("onset_f1_20ms", "C1_timing_jitter")]
add("BlFOneTwentyJitter", m(r["song_mean_by_dose"]["d3"], 3), "onset_f1_20ms/C1: song mean at +-30 ms (exactly 1 at +-10, +-20 ms)")
d, lo, hi = raw_contrast(r)
add("BlFOneTwentyJitterDelta", m(d, 3, True), "onset_f1_20ms/C1: strongest minus matched control")
add("BlFOneTwentyJitterDeltaCI", ci(lo, hi, 3), "onset_f1_20ms/C1: 99.5% CI")
dc = DC["distinct_4|C3_type_shuffle"]
add("BlDistinctFourShuffleDelta", m(dc["delta"], 2, True), "verify/distinct_ci.json: distinct_4|C3 delta (rise under note-type shuffle)")
add("BlDistinctFourShuffleDeltaCI", ci(*dc["delta_ci995"], 2), "verify/distinct_ci.json: distinct_4|C3 99.5% CI")
add("BlNSongs", str(cell[("lm_perplexity", "C1_timing_jitter")]["n_songs"]), "n_songs (every cell)")
assert all(r["n_songs"] == 80 for r in R["results"])

M = ["% AUTO-GENERATED by make_tex.py from baseline_final_results.json, verify/crosslm_c5_heldout.json,",
     "% verify/distinct_ci.json. POST HOC SECONDARY held-out analysis (not prespecified).",
     "% Song means (mean over courses within song, then over the 80 songs); CIs are 99.5% song-bootstrap."]
for name, value in macros:
    M.append(f"\\newcommand{{\\{name}}}{{{value}}}% {src[name]}")
(HERE / "baseline_numbers.tex").write_text("\n".join(M) + "\n")

vm = {"analysis": "POST_HOC_SECONDARY_heldout_baselines_FINAL", "rows": [b for b, _ in ROWS] + ["chartgeneval_measurement"],
      "cols": [p for p, _ in COLS], "matrix": matrix,
      "cells": {f"{b}|{p}": {k: cell[(b, p)][k] for k in ("label", "frozen_rule_verdict", "n_songs", "dose_statistic_mean", "dose_ci995",
                                                           "contrast_mean", "contrast_ci995", "sham", "sham_rule", "report_as",
                                                           "song_mean_by_dose", "fraction_replicates_equal_unedited_by_dose")}
                | {"raw_contrast_strongest_minus_control": raw_contrast(cell[(b, p)])}
                for b, _ in ROWS for p, _ in COLS},
      "macros": {n: {"value": v, "source": src[n]} for n, v in macros},
      "source_sha256": hashlib.sha256((HERE / "baseline_final_results.json").read_bytes()).hexdigest()}
(HERE / "verdict_matrix.json").write_text(json.dumps(vm, indent=1))
for b in vm["rows"]:
    print(f"{b:26s}", " ".join(f"{matrix[b][p][:7]:8s}" for p, _ in COLS))
