"""Build Table 2 (post hoc secondary analysis) from the verdict-matrix snapshot.

Reads tables/baselines_verdict_matrix.json (a byte-identical copy of
artifacts/posthoc_baselines_heldout/verdict_matrix.json) and writes tables/baselines.tex.
Only symbols are printed; every symbol is the recorded label of one cell.
"""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "baselines_verdict_matrix.json"
VM = json.loads(SRC.read_text())
assert VM["analysis"] == "POST_HOC_SECONDARY_heldout_baselines_FINAL"

# Rows: the nine edits in Table 1 order; columns: statistics.
EDITS = [("C1_timing_jitter", "Timing jitter"), ("C1s_sparse_jitter", "Sparse timing errors"),
         ("C2_anchor_shift", "Whole-chart shift"), ("C3_type_shuffle", "Note-type shuffle"),
         ("C4_loop_collapse", "Loop replacement"), ("C5_blandification", "Common-pattern rewrite"),
         ("C8_bar_shuffle", "Window shuffle"), ("C6_density_scale", "Note-rate scaling"),
         ("C7_burst_insert", "Burst insertion")]
STATS = [("lm_perplexity", "PPL"), ("self_similarity", "SS"), ("ioi_hist_js", "JS"),
         ("onset_f1_50ms", "F1$_{50}$"), ("onset_f1_20ms", "F1$_{20}$"),
         ("chartgeneval_measurement", "Target")]
SYM = {"DETECTS": r"\checkmark", "BLIND": r"$\circ$", "REWARDS": r"$\times$",
       "N/A-by-design": "--"}
assert sorted(VM["cols"]) == sorted(e for e, _ in EDITS)
assert sorted(VM["rows"]) == sorted(s for s, _ in STATS)
for s, _ in STATS[:-1]:
    for e, _ in EDITS:
        c = VM["cells"][f"{s}|{e}"]
        assert c["n_songs"] == 80 and c["label"] == VM["matrix"][s][e], (s, e)
        if c["label"] == "REWARDS":
            assert c["dose_ci995"][0] > 0 and c["contrast_ci995"][0] > 0, (s, e)

sha = hashlib.sha256(SRC.read_bytes()).hexdigest()
# Columns: edits numbered in the row order of Table 1, grouped by property as there.
GROUPS = [("Timing", 3), ("Pattern", 1), ("Repetition", 3), ("Density", 2)]
assert sum(n for _, n in GROUPS) == len(EDITS)
LABELS = {"lm_perplexity": "Perplexity", "self_similarity": "Self-similarity",
          "ioi_hist_js": "IOI-histogram JS", "onset_f1_50ms": "Onset F1, 50\\,ms",
          "onset_f1_20ms": "Onset F1, 20\\,ms", "chartgeneval_measurement": "Target measurement"}
L = [f"% AUTO-GENERATED by tables/build_baselines.py from baselines_verdict_matrix.json (sha256 {sha[:16]}).",
     "% POST HOC SECONDARY analysis, not prespecified. Columns 1-9: " + ", ".join(n for _, n in EDITS) + ".",
     r"\begin{tabular}{@{}l" + "c" * len(EDITS) + "@{}}", r"\toprule"]
heads, rules, col = [], [], 2
for name, n in GROUPS:
    heads.append(rf"\multicolumn{{{n}}}{{c}}{{{name}}}")
    rules.append(rf"\cmidrule(lr){{{col}-{col + n - 1}}}")
    col += n
L.append("Statistic & " + " & ".join(str(i) for i in range(1, len(EDITS) + 1)) + r" \\")
L.append(r"\midrule")
# The ChartGenEval row is omitted: each target measurement was tested on one edit only
# (Table 1), so a 9-column row would read as a scoreboard.
for s_, _ in STATS[:-1]:
    L.append(LABELS[s_] + " & " + " & ".join(SYM[VM["matrix"][s_][e]] for e, _ in EDITS) + r" \\")
L += [r"\bottomrule", r"\end{tabular}"]
(HERE / "baselines.tex").write_text("\n".join(L) + "\n")
print(f"wrote tables/baselines.tex from {SRC.name} ({sha[:16]})")
